name: Databricks CI/CD

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  deploy:
    name: Deploy Bundle
    runs-on: ubuntu-latest
    environment: prod_env

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Deploy bundle
        run: databricks bundle deploy --target prod
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

  run_job:
    name: Run Finance Pipeline
    runs-on: ubuntu-latest
    needs: deploy
    environment: prod_env

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Run finance pipeline
        run: databricks bundle run finance_pipeline --target prod
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

  unit_testing:
    name: Data Quality Tests
    runs-on: ubuntu-latest
    environment: prod_env
    needs: run_job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Run data quality tests
        run: databricks bundle run unit_tests --target prod
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

